### ISSUE TITLE
Toggle/collapse Container Content

### ISSUE THREAD

**Issue by jacobsenj** [b13/container#167] opened 2021-07-16 11:36 UTC
Would it be possible to toggle the container content in the Backend?

In another grid extension the contents can be toggled/collapsed:
![image](https://user-images.githubusercontent.com/399303/125941940-d00750f1-0ec4-4d82-aa06-3f67de4b67bf.png)

**Comment by georgringer** [comment] 2021-07-21 09:15
duplicate of https://github.com/b13/container/issues/123

**Closed** 2021-08-12 11:39 UTC
