### ISSUE TITLE
no renderin of b13_container elements when "mask" is active

### ISSUE THREAD

**Issue by fgerards** [b13/container#183] opened 2021-08-11 21:01 UTC
I cannot render any b13_container elements after masks typoscript is included - how can this be solved ? how does b13_container modify normal content rendering and mask content rendering ?

**Comment by achimfritz** [comment] 2021-08-13 05:37
how exactly can i reproduce this case (i installed mask and add the TS via "include static" in my root-TS, everything works fine.
this is the mask TypoScript? https://github.com/Gernott/mask/blob/master/Configuration/TypoScript/setup.typoscript
(looks harmless)
EXT:container comes with no TypoScript.
Please give me more informations about your setup

**Comment by fgerards** [comment] 2021-08-18 09:10
hi,
i use ofc FSC and let the content render on the page to the page templates with

         `variables {
            content < styles.content.get
.....`

turned out, that mask typoscript setup has to be included AFTER my typoscript config so the mask-snippet and therefore content is rendered ... still didnt figure out why this is so and why styles.content.get of the FSC-core-extension eliminates the mask rendering

**Comment by achimfritz** [comment] 2021-08-18 10:01
Hi @fgerards ,

so this is not a issue with EXT:container? right?

the EXT:mask also add TypoScript automatically, s. https://github.com/Gernott/mask/blob/master/Classes/CodeGenerator/TyposcriptCodeGenerator.php#L172 , could this be the reason? 

try `content =< styles.content.get` (s. https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ApiOverview/TypoScriptSyntax/Syntax/TypoScriptSyntax.html#object-copying-the-sign "Note"

**Comment by fgerards** [comment] 2021-08-20 10:34
styles.content.get behaviour seems deprecated - will use dynamic-content-mapping snippet of TYPO3 docu.

**Comment by achimfritz** [comment] 2021-09-28 17:42
i close this issue.

**Closed by achimfritz** 2021-09-28 17:42 UTC
