### ISSUE TITLE
Children of nested containers loose their parent, when moved in a workspace

### ISSUE THREAD

**Issue by IndyIndyIndy** [b13/container#429] opened 2023-07-27 08:37 UTC
The following scenario: 
- We have a collapse container
- The collapse container itself can only contain container elements of type "container-element"
- The container element itself can contain any normal content like textmedia, etc.

Example code: https://gist.github.com/IndyIndyIndy/1ecb0ed4684e2f50223217d9fa7937fe

If you create such a nested container structure in live workspace, then switch to another workspace and try to move its children to a new collapse, the lower children loose their parent.
Could be related to: https://github.com/b13/container/issues/259

How to reproduce
- In live workspace create a **container-collapse**
- Then create a **container-element** inside the collapse
- Then create a textmedia elemnt inside the container-element
- Now switch to another workspace
- Create a second **container-collapse** at the bottom of the page
- Now via drag and drap, drag the **container-element** of the first collapse into the second collapse.
- Reload the page. Now you should notice, that the textmedia inside the **container-element** has lost its parent container and is shown in **unused**.

**Comment by achimfritz** [comment] 2023-08-08 16:46
sorry, i cannot reproduce, i have tried
step 1-3
```
MariaDB [db]> select t3ver_wsid,uid,t3ver_oid,CType,tx_container_parent,header from tt_content;
+------------+-----+-----------+---------------------------------+---------------------+--------------------+
| t3ver_wsid | uid | t3ver_oid | CType                           | tx_container_parent | header             |
+------------+-----+-----------+---------------------------------+---------------------+--------------------+
|          0 |   1 |         0 | b13-2cols                       |                   0 | container-collapse |
|          0 |   2 |         0 | b13-2cols-with-header-container |                   1 | container-element  |
|          0 |   3 |         0 | textmedia                       |                   2 | text media         |
+------------+-----+-----------+---------------------------------+---------------------+--------------------+
```
step 4+5:
```
MariaDB [db]> select t3ver_wsid,uid,t3ver_oid,CType,tx_container_parent,header from tt_content;
+------------+-----+-----------+---------------------------------+---------------------+---------------------------+
| t3ver_wsid | uid | t3ver_oid | CType                           | tx_container_parent | header                    |
+------------+-----+-----------+---------------------------------+---------------------+---------------------------+
|          0 |   1 |         0 | b13-2cols                       |                   0 | container-collapse        |
|          0 |   2 |         0 | b13-2cols-with-header-container |                   1 | container-element         |
|          0 |   3 |         0 | textmedia                       |                   2 | text media                |
|          1 |   4 |         0 | b13-2cols                       |                   0 | second container-collapse |
+------------+-----+-----------+---------------------------------+---------------------+---------------------------+
```
step 6
```
MariaDB [db]> select t3ver_wsid,uid,t3ver_oid,CType,tx_container_parent,header from tt_content;
+------------+-----+-----------+---------------------------------+---------------------+---------------------------+
| t3ver_wsid | uid | t3ver_oid | CType                           | tx_container_parent | header                    |
+------------+-----+-----------+---------------------------------+---------------------+---------------------------+
|          0 |   1 |         0 | b13-2cols                       |                   0 | container-collapse        |
|          0 |   2 |         0 | b13-2cols-with-header-container |                   1 | container-element         |
|          0 |   3 |         0 | textmedia                       |                   2 | text media                |
|          1 |   4 |         0 | b13-2cols                       |                   0 | second container-collapse |
|          1 |   5 |         2 | b13-2cols-with-header-container |                   4 | container-element         |
|          1 |   6 |         3 | textmedia                       |                   2 | text media                |
+------------+-----+-----------+---------------------------------+---------------------+---------------------------+
```
BE looks:
![image](https://github.com/b13/container/assets/2152991/208cea74-c5ff-4708-8663-9edf8b0775a5)
(testet with current EXT:container in TYPO3 11 and 12)

**Comment by IndyIndyIndy** [comment] 2023-08-22 06:50
Tested around a bit and found the culprit: It's another third-party extension on top of ext:container, that internally changes some of the behaviour when moving/copying container elements: **team23/t23-inline-container**
Will have a closer look into that extension.

**Comment by achimfritz** [comment] 2023-09-13 14:37
i think we should close this issue here, and move it to team23/t23-inline-container

**Closed by achimfritz** 2023-09-13 14:37 UTC
