### ISSUE TITLE
Drag and drop of elements into containers kicks the colPos of the element

### ISSUE THREAD

**Issue by HorstBaumann** [b13/container#297] opened 2022-09-07 12:04 UTC
**System:**
    TYPO3 11.5.15 - fresh installation
    container 2.0.2

**Description:**
After updating container from 1.6.1 to 2.* it is no longe possible to move an element from outside a container into a container or 
vice versa. The element loses its colPos.
When I downgrade to container 1.6.1 everything works well.

**Error:** 
These fields of record xx in table "tt_content" have not been saved correctly: colPos! The values might have changed due to type casting of the database.

![2022-09-07_13h51_19](https://user-images.githubusercontent.com/11771888/188871791-b84abf23-26b5-4345-9e4c-1a3a5b3479be.png)

**Comment by achimfritz** [comment] 2022-09-07 12:13
@HorstBaumann mh, cannot reproduce, did you run the container-sorting migration? `bin/typo3cms container:sorting 0` if you have already content elements in the database?

**Comment by HorstBaumann** [comment] 2022-09-07 12:16
no. how can i run this ? (no composer setup)

**Comment by achimfritz** [comment] 2022-09-07 12:19
use upgrade wizard

**Comment by HorstBaumann** [comment] 2022-09-07 13:02
OK, i used the upgrade wizard. But the problem remains.

php: 8.1.7

**Comment by achimfritz** [comment] 2022-09-07 14:38
What database do you running, colPos is an integer field in Database, so the error you get looks like we give colPos as a string to the datahandler.
I try to reproduce.

**Comment by HorstBaumann** [comment] 2022-09-07 15:04
colPos is correctly set to:  int(10) unsigned [0]

I discovered, that after moving the element, the uid of the new parent-container is wrongly written to the colPos-column.
and the column "tx_container_parent" does not change.

**example:**
element E was build inside container A (uid11)
element E has colPos = 201 and tx_container_parent = 11

now i move element E to a new container B (uid12)
-the backend shows me the error-
and element E now has colPos = 12 and tx_container_parent = 11

(when i drop it directly to the page (not inside a container-element) the colPos is correctly updated to 0, but tx_container_parent stays on the uid of the last surrounding container - which causes the backend to put the element to the "unused-area")

I think there must be an error by updating colPos and tx_container_parent while dropping the contained element to the new destination.


![grafik](https://user-images.githubusercontent.com/11771888/188906889-ee59973d-a449-45d8-8789-9fbdc077d6ae.png)

**Comment by achimfritz** [comment] 2022-09-09 06:48
@HorstBaumann sorry, cannot reproduce... Can you give me more Information, would be cool to have your Container-Configuration, your Backend-Layout, and a dump of tt_content before moving the element

**Comment by Adan0s** [comment] 2022-09-12 08:07
I'm having the same problem with version 2.0.4. Never used the 1.x branch as I just migrated a week ago from gridelements to container. 

![image](https://user-images.githubusercontent.com/1481532/189603763-abfe8fec-25cc-4ca6-a1fc-78542667fe30.png)

**Comment by HorstBaumann** [comment] 2022-09-12 11:21
@Adan0s very good point ! - I also use "paste_reference 2.0.0" - which seems to cause the problem in combination with container (higher than 1.6.1)

Isn't there another way to bring back the "paste as reference" core-function to TYPO3 v11 ?

**Comment by achimfritz** [comment] 2022-09-16 10:24
the EXT:paste_reference uses a mix of data and cmd when moving elements like
```
data = [
    'tt_content' => [
        'colPos' => 10,
        'sys_language_uid' => 0
    ]
];
cmd = [
    'tt_content' => [
        1 => ['move' => 139]
    ]
];
```

support for this mix has been removed in 2.0
also the core has removed this mix (because of Problems in WS)
s. https://forge.typo3.org/projects/typo3cms-core/repository/1749/revisions/c1be5540b20421fdfa295a1323b663f3189a41d7 and https://forge.typo3.org/issues/92849

the EXT:paste_reference datahandler call in the JS should change to:

```
data = null;
cmd = [
  'tt_content' => [
      1 => [
          'move' => [
              'action' => 'paste',
              'target' => 139,
              'update' => [
                  'colPos' => 10,
                  'sys_language_uid' => 0
              ]
          ]
      ]
  ]
];

```

i will provide an PR

**Comment by achimfritz** [comment] 2022-09-16 10:39
https://github.com/Kephson/paste_reference/pull/7

**Comment by CMS-Internetsolutions** [comment] 2022-10-05 14:52
Shortly to the info, the extension "paste_reference" caused with me also the errors indicated above.

**Comment by achimfritz** [comment] 2022-11-03 11:58
should be fixed using current Version of EXT:past_reference (>=2.0.1)

**Closed by achimfritz** 2022-11-03 11:58 UTC

**Comment by mikestreety** [comment] 2022-11-21 14:08
As an update, a new version of paste reference (1.0.3) has been released to address and resolve this issue:

https://github.com/Kephson/paste_reference/commit/2c8dfea5f14e574abf14173047a853d1f21155b8
