### ISSUE TITLE
Minimize required typoscript configuration 

### ISSUE THREAD

**Issue by davidsteeb** [b13/container#25] opened 2020-07-11 16:25 UTC
I would like to see a way to minimize the TypoScript configuration required, and assign the content for each colPos to a variable for Fluid automatically. This way a smaller TypoScript setup like this

```
tt_content.2col-container =< lib.contentElement
tt_content.2col-container {
  templateName = 2col-container
  dataProcessing.13 = B13\Container\DataProcessing\ContainerProcessor
}
```

could achieve the same result as this snippet:

```
tt_content.2col-container =< lib.contentElement
tt_content.2col-container {
  templateName = 2col-container
  dataProcessing {
    201 = B13\Container\DataProcessing\ContainerProcessor
    201 {
      colPos = 201
      as = children_201
    }
    202 = B13\Container\DataProcessing\ContainerProcessor
    202 {
      colPos = 201
      as = children_202
    }
}
```

by automatically assigning every available column to a default variable name.

**Comment by ervaude** [comment] 2020-07-13 08:48
Closed as dupe of #27

**Closed by ervaude** 2020-07-13 08:48 UTC
