### ISSUE TITLE
container:sorting --apply does nothing whereas upgrade wizard does

### ISSUE THREAD

**Issue by christophlehmann** [b13/container#367] opened 2023-02-21 08:55 UTC
In TYPO3 11 with EXT:container v2.1.2 the command `container:sorting --apply` can be executed multiple times and nothing happens. The Sorting Upgrade Wizard works as expected (web execution).

**Comment by achimfritz** [comment] 2023-02-22 06:21
@christophlehmann , mh i cannot reproduce this bug, ich have wrong sorting tt_content:
```
MariaDB [db]> select uid,header,CType,sorting from tt_content;
+-----+--------------+---------------------------------+---------+
| uid | header       | CType                           | sorting |
+-----+--------------+---------------------------------+---------+
|   1 | container-el | b13-2cols-with-header-container |     512 |
|   2 | child-el     | header                          |     256 |
+-----+--------------+---------------------------------+---------+
```
i run the migration command (twice, to show migration is finished):
```
af@core11-web:/var/www/html$ vendor/bin/typo3 container:sorting --apply
container uid: 1, pid 1 must be fixed
af@core11-web:/var/www/html$ vendor/bin/typo3 container:sorting --apply
migration finished
af@core11-web:/var/www/html$ 
```
sorting is fixed in db
```
MariaDB [db]> select uid,header,CType,sorting from tt_content;
+-----+--------------+---------------------------------+---------+
| uid | header       | CType                           | sorting |
+-----+--------------+---------------------------------+---------+
|   1 | container-el | b13-2cols-with-header-container |     512 |
|   2 | child-el     | header                          |     768 |
+-----+--------------+---------------------------------+---------+
```

can you give more hints?

**Comment by christophlehmann** [comment] 2023-03-03 09:16
@achimfritz Thanks for verification. I will debug it to find the differences between web and console execution

**Comment by SSFGizmo** [comment] 2023-03-05 17:54
@achimfritz 

TYPO3 11.5.24
PHP 7.4
Container 2.2.0 

When I try to execute, 

`vendor/bin/typo3 container:sorting --apply`

I get this message

```
In ErrorHandler.php line 137:

  PHP Warning: mysqli_stmt::free_result(): Couldn't fetch mysqli_stmt 
in /vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/Mysqli/MysqliStatement.php line 557
```

This works
`vendor/bin/typo3 container:sorting dryrun`

* https://github.com/b13/container/blob/2.2.0/Classes/Integrity/Sorting.php

Lines: 123 and 146
`'colPos' => $container->getUid() . '-' . $child['colPos'],`

Are they correct?

**Comment by christophlehmann** [comment] 2023-03-07 21:53
Okay, found it. `$GLOBALS['BE_USER']->user['admin'] = 1;` in `\B13\Container\Command\SortingCommand::execute()` made it. 

There was a backend user named `_cli_` which is not an admin. Might be historically, that it is no admin, don't know.

What do we do with the issue,  close? Extend docs? Or add such line or a warning?

**Comment by kitzberger** [comment] 2023-04-26 11:00
Had the same issue here, calling `vendor/bin/typo3 container:sorting --apply` didn't do nothing, because `_cli_` wasn't allowed to modify tables (because it wasn't an admin or part of any editors group).

Apparently `_cli_` should be an admin, didn't know that either. But the autogenerated `_cli_` (in case it's missing) is one. See https://github.com/TYPO3/typo3/blob/main/typo3/sysext/core/Classes/Authentication/CommandLineUserAuthentication.php#L157-L170

Maybe render something useful to the CLI so others don't have to debug thru DataHandler in order to find out what's the matter here? Or mention this extensions CLI tasks in some docs here with some helpful trouble shooting hints?

**Comment by achimfritz** [comment] 2023-10-18 07:28
Hi Guys,

i have added a new option `enable-logging` for the command, that enables datahanders logging. Enable this and have a look into the TYPO3 Log Module (EXT:container 2.3.1, s https://github.com/b13/container/pull/450/commits/1f0b4f26adf4b717ce0888de6713c29f5b0af727)

**Closed by achimfritz** 2023-10-18 07:28 UTC
