### ISSUE TITLE
Copying container with multiple levels of child elements does only set the `sys_language_uid` correctly for the first child level

### ISSUE THREAD

**Issue by DenisMir** [b13/container#240] opened 2022-03-08 08:35 UTC
We got a bug with container version 1.4.2 and 1.5.0 with TYPO3 10LTS and 11LTS (latest patch versions). 

Copying constructs like

Main Container 
-> Sub Container
  -> Element or Sub Sub Container

to another language does only set the `sys_language_uid` for the first child level correctly. All the other elements that are deeper in the tree get `sys_language_uid` set to the source `sys_language_uid`. (-> they are invisible in the page module) 

This leads to something like: 

![Bildschirmfoto 2022-03-08 um 09 09 06](https://user-images.githubusercontent.com/157281/157197058-84752b9a-6550-4825-97f9-9e44d8e75718.png)

Another example: 

![Bildschirmfoto 2022-03-08 um 09 28 24](https://user-images.githubusercontent.com/157281/157197175-e00c933a-5526-48bb-8d6f-7938be90f2ae.png)

Database view of the second example (querying for the inserted records in `tt_content`): 
![Bildschirmfoto 2022-03-08 um 09 33 19](https://user-images.githubusercontent.com/157281/157198303-229dfb0c-8b09-4ab0-b8de-f33fb51d5ae2.png)

Any ideas what the problem could be?

**Comment by achimfritz** [comment] 2022-03-09 16:50
Hi @DenisMir , do you really "copy" the element to an other language? you should use translate (wizard), and choose copy (free mode) or translate (connected mode, "preferred")
![image](https://user-images.githubusercontent.com/2152991/157489983-9d6da1a4-1dbb-4305-a040-58100303c16d.png)
(otherwise than realy use "copy", i can not reproduce the issue)

**Comment by DenisMir** [comment] 2022-03-10 08:05
Yes we indeed do "copy" not "translate copy". It is often necessary to copy structures from one pages default language to another pages second language. 
Even when already having a page that is translated in two languages it is often necessary to copy only bits of the default language to other ones as well. 
The frontend offers this functionality so I would assume that a "normal" copy should work as well or am I mistaken?

**Comment by pixelpublic** [comment] 2022-03-10 10:59
Hi @achimfritz - I think we have the same issue here (Version 1.5.0)

**1st try:**
I create a new translation for the page "Konzept" (EN: Concept). 
Then, I create the translations of the content element and selected English language as localisation source. Some elements were translated, others showed errors and the translations of the nested elements are not available.
 

**2nd try:**
I create a new translation for the page "Konzept" (EN: Concept). 
Then, I create the translations of the content element and selected German language as localisation source. Now, everything works fine. 

We need to fix this behavior. Do you have any idea how to solve this? 

I created a video which shows the problem - please have a look here.
https://vimeo.com/686646832/b14ea006e3

**Comment by achimfritz** [comment] 2022-03-10 12:45
Hi @pixelpublic , your issue looks like https://github.com/b13/container/issues/232 , and should be already fixed on master branch, can you test it on master branch? (then i will release a new version)

**Comment by pixelpublic** [comment] 2022-03-11 08:26
@achimfritz thank you! It works perfectly now! Thank you!!!

**Comment by DenisMir** [comment] 2022-03-18 06:50
@achimfritz Any idea where this problem could develop? I would debug a bit to find the reason for it.

**Comment by DenisMir** [comment] 2022-03-22 13:15
Ok I did find the reason for the error. 

For now I can only say that the way container does make the nested copy work does not allow it to set the correct `sys_language_uid` when having a nesting level deeper than one. 

In the `DatamapBeforeStartHook` there is a `datamapForChildrenChangeContainerLanguage` that updates the child to the `sys_language_uid` of its parent. 

```
$datamapForLocalizations['tt_content'][$child['uid']] = [
  'sys_language_uid' => $data['sys_language_uid']
];
```
But this does only work when the current record is the root record which got `sys_language_uid` in the data map set to the foreign language. Now the first child (first level) gets delivered with the correct `sys_language_uid`. But the deeper levels don't profit from that one since their parent is a container record itself which still got `sys_language_uid` set to the source value. 

So with this approach it can't work for deeper levels. 

Wouldn't it be easier to use the `CommandMapPostProcessingHook` and its `copyOrMoveChildren` method to set the `sys_language_uid` already correctly? The `DataHandler $dataHandler` is given as parameter and it contains the `cmdmap` of the parent item. With that one the datamap can be read and the `root` one does contain the `sys_language_uid`. This way every level gets the correct `sys_language_uid`.

**Comment by achimfritz** [comment] 2022-04-02 15:03
@DenisMir sorry for long waiting ... you are right, copy to other language should work, i have add sys_language_uid on cmdmap when copy/move children of container
(the `DatamapBeforeStartHook` is "outdated", also needed for TYPO3 9, i make a remark in the Class)

**Comment by DenisMir** [comment] 2022-04-05 06:17
Awesome thank you very much. This will help our editors big time when it is live.

**Closed** 2022-04-05 07:39 UTC

**Comment by DenisMir** [comment] 2022-04-06 06:45
@achimfritz Have you got an idea when you are able or plan to release the next bugfix release?
