### ISSUE TITLE
New drag and drop feature in v13 does not work if EXT:container is installed

### ISSUE THREAD

**Issue by wowaTYPO3** [b13/container#533] opened 2024-09-12 18:49 UTC
In TYPO3 13.3.0-dev a new feature for cross-page drag'n drop for content elements has been introduced, see https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/13.3/Feature-104935-AllowMovingContentElementsViaPageTree.html#feature-104935-allow-moving-content-elements-via-page-tree

This does not work if dev-master of EXT:container is installed.

In the browser console you can see that the URL is not correct.
https://vt13.ddev.site/undefined?expandPage=13&originalPid=13

This is what it should look like:
https://13test.ddev.site/typo3/record/move?token=caff8cf4312adee7a843d3c567d2607f1a303dd7&uid=2&originalPid=2&expandPage=2&returnUrl=%2Ftypo3%2Fmodule%2Fweb%2Flayout%3Ftoken%3D4c09829fc6f0856efa87b937d880d388fd1344a1%26id%3D1

Tested in 2 different TYPO3 instances.

**Comment by bmack** [comment] 2024-09-12 19:08
Hey @wowaTYPO3 ,

yes. that's a "known" issue since a few hours (when the new feature was merged). As far as I heard, there are a few more changes coming to the page module in 13.3 (scheduled for tuesday) that's why we might need a few days to coordinate EXT:container development with the Core changes.

**Comment by wowaTYPO3** [comment] 2024-09-12 19:59
Thanks for the super-fast reply. Are you going to call it a day at some point? ;)

I'm looking forward to the new version (I'll also be showing the extension again in my new video course).

**Closed** 2024-10-15 05:55 UTC

**Comment by wowaTYPO3** [comment] 2024-11-15 11:07
The problem occurs again in a TYPO3 13.4.1 with container 3.1.0.
![2024-11-15_12-06-21](https://github.com/user-attachments/assets/58030501-fc91-4706-a8e0-11ebbb88f6a1)

**Comment by achimfritz** [comment] 2024-11-17 16:04
Hi @wowaTYPO3 , i cannot reproduce your error report, i tried to move a container-child element to another page, an it works. i see this urls
<img width="1485" alt="Screenshot 2024-11-17 at 16 59 55" src="https://github.com/user-attachments/assets/d5578815-6fc4-4298-a818-8f53cd6ccd2e">
