### ISSUE TITLE
container 1.3.0: names of colPos 

### ISSUE THREAD

**Issue by Hobokens** [b13/container#142] opened 2021-03-18 16:25 UTC
Hi,
I have several templates with the same colPos numbers.

typo3conf/ext/my_sitepackage/Configuration/TCA/Overrides/1col-container.php
```
\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\B13\Container\Tca\Registry::class)->configureContainer(
    (
    new \B13\Container\Tca\ContainerConfiguration(
        '1col-container',
        '1 Spalte',
        'Breite: 100%',
        [
            [
                ['name' => 'Spalte: 100%', 'colPos' => 201]
            ]
        ] // grid configuration
    )
    )
);
```
typo3conf/ext/my_sitepackage/Configuration/TCA/Overrides/2cols-container.php
```
\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\B13\Container\Tca\Registry::class)->configureContainer(
    (
    new \B13\Container\Tca\ContainerConfiguration(
        '2cols-container',
        '2 Spalten (1/1)',
        'Breite: jeweils 50%',
        [
            [
                ['name' => 'linke Spalte: 50%', 'colPos' => 201],
                ['name' => 'rechte Spalte: 50%', 'colPos' => 202]
            ]
        ] // grid configuration
    )
    )
);
```
typo3conf/ext/my_sitepackage/Configuration/TCA/Overrides/2cols-container.php

```
\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\B13\Container\Tca\Registry::class)->configureContainer(
    (
    new \B13\Container\Tca\ContainerConfiguration(
        '3cols-container',
        '3 Spalten (1/1/1)',
        'Breite: jeweils 33%',
        [
            [
                ['name' => 'linke Spalte: 33%', 'colPos' => 201],
                ['name' => 'mittlere Spalte: 33%', 'colPos' => 203],
                ['name' => 'rechte Spalte: 33%', 'colPos' => 202]
            ]
        ] // grid configuration
    )
    )
);
```
If I choose the container '3 Spalten (1/1/1)' the cols have the following names 'Spalte: 100% ', 'mittlere Spalte: 33%', 'rechte Spalte: 50% '

I don't have this problem with container 1.2

Second Problem: I miss  container in the page wizard (s. image 
container 1.2.
![cotaniner_1 2](https://user-images.githubusercontent.com/6764582/111660537-793ea380-880e-11eb-8fd1-44da14ef3fb1.png)
container 1.3
![container_1 3](https://user-images.githubusercontent.com/6764582/111660585-852a6580-880e-11eb-9a75-ce8c1335907a.png)

TYPO3 10.4.14

**Comment by achimfritz** [comment] 2021-03-19 07:49
@Hobokens thanks for reporting, i can reproduce the first problem and will provide a bugfix soon, but i cannot reproduce the second problem with the new Content Element Wizard, mh, any special Configurations? PageTsLoading has changed from SignalSlot to Event, do you see the Event-Registration in the Configuration Module?

![pageTsConfigEvent](https://user-images.githubusercontent.com/2152991/111747485-a97a5680-888f-11eb-803f-e8bde7d84a7b.png)

What happens if you reactivate the signal slot in `ext_localconf.php` (s. line 9 in EXT:container/ext_localconf.php)

```
\TYPO3\CMS\Core\Utility\GeneralUtility::makeInstance(\TYPO3\CMS\Extbase\SignalSlot\Dispatcher::class)->connect(
            \TYPO3\CMS\Backend\Utility\BackendUtility::class,
            'getPagesTSconfigPreInclude',
            B13\Container\Tca\Registry::class,
            'addPageTS'
        );
```

do you have EXT:content_defender installed? What is your PHP-Version?

**Comment by Hobokens** [comment] 2021-03-19 10:17
@achimfritz 
Thank you for taking care of it so quickly. 
Following your hints I reactivated the signal slot in ext_localconf.php and then deactivated it again. Now 'container' is displayed in the Content Element Wizard. The reason for this I have not understood in the end, but the main thing is that it works.
I use PHP 7.3. and no content_defender.

**Comment by achimfritz** [comment] 2021-03-21 15:17
fixed with https://github.com/b13/container/pull/143

**Closed by achimfritz** 2021-03-21 15:17 UTC
