### ISSUE TITLE
Screen is frozen when changing Ctype in backend in a container

### ISSUE THREAD

**Issue by xbouillet** [b13/container#243] opened 2022-03-22 09:08 UTC
Hello,

We use container 1.5.0 with a TYPO3 11.5.6.

In backend, on a container, if we want to change the Ctype to use another container, we have a bug. Screen is frozen like a javascript alert.

Any idea ?

Thanks

**Comment by achimfritz** [comment] 2022-04-02 11:04
Hi @xbouillet , mh, cannot reproduce, can you give more informations? (your container-config? PHP-Version?, Dump of tt_content table this error occurs? EXT:content_defender installed? other extensions?)

**Comment by achimfritz** [comment] 2022-05-11 05:58
Hi @xbouillet , any news? else i will close the issue

**Comment by achimfritz** [comment] 2022-06-03 09:11
closed due no feedback

**Closed by achimfritz** 2022-06-03 09:11 UTC
