### ISSUE TITLE
pi_flexform is not saved after creating new container element

### ISSUE THREAD

**Issue by samuel-lobby** [b13/container#376] opened 2023-03-16 12:20 UTC
When I create a new container element, the pi_flexform is not saved in the database. I get a value of null in the dump. If I open the newly created container element and manually save it again, the flexform configuration is applied.

Reproducible under TYPO3 11.5.24 & 11.5.25 with container version 2.1.0 & 2.2.0.

**Comment by kitzberger** [comment] 2023-03-27 17:22
@samuel-lobby, I can confirm this behaviour when creating container elements via the page module.

TCAdefaults are considered though, e.g. `TCAdefaults.tt_content.header = 123`

**Comment by kitzberger** [comment] 2023-03-28 19:15
@samuel-lobby, workaround: set `saveAndCloseInNewContentElementWizard(false)` for your container.

**Comment by samuel-lobby** [comment] 2023-03-29 07:51
@kitzberger thanks for your answer. I'll check it the next days and will write a feedback down here.

**Comment by achimfritz** [comment] 2023-03-30 14:30
Hi Guys, looks like a core issue, because `saveAndClose` is a core feature, not an EXT:container, the only thing EXT:container does is to add  `saveAndClose` to the new content elments wizard item
s. https://docs.typo3.org/c/typo3/cms-core/11.5/en-us/Changelog/10.3/Feature-90461-QuickCreateContentElementsViaNewContentElementWizard.html
(and maybe https://forge.typo3.org/issues/91997)

therefore i close this issue

**Closed by achimfritz** 2023-03-30 14:30 UTC
